improve inspkg

diff --git a/inspkg b/inspkg
--- a/inspkg
+++ b/inspkg
@@ -24,77 +24,97 @@ pkgfile=$(realpath $1)
 pf=$(basename $1)
 pf=${pf%.tar*}
 tmpdir=$pkgs/tmp/$pf
-listname=$pf.list
+#listname=$pf.list
+
+list=.LIST
+info=.INFO
+etc=.ETC
+failed=.FAILED
+conflict=.CONFLICT
 
 mk_dir $tmpdir
 cd $tmpdir
 
-tar xf $pkgfile || exit $E_CMDFAILED
+tar xf $pkgfile || exit $E_BADARCHIVE
 
-if [ ! -e .LIST ]; then
-    echo ".LIST not found in package. Exiting"
+if [ ! -e $list ]; then
+    echo "$list not found in package. Exiting"
     exit $E_BADPKG
 fi
 
-cp .LIST .TMP
+parse_list # it handles collision, check for infos and etcs
 
-check_collision .LIST # it handles etc collision automatically
-
-while read -u 4 file
+while read -u 4 file # $file should be like "usr/lib/libfoo", without leading /
 do
     if [ ! -e $file ]
     then
         echo $file not found
         exit $E_BADFILE
-    elif [ -d $file -a ! -L $file ]
-    then
-        mk_dir /$file
+    elif [ -d $file ]; then
+        if [ -f /$file ]
+            echo "/$file is not a directory, but $file is. Exiting..."
+            exit $E_BADDIR
+        elif [ ! -L $file ]; then
+            mk_dir /$file
+        elif [ ! -e /$file ]; then
+            cp --preserve=mode --no-dereference $file /
+        else
+            echo "/$file is symlink to directory $(readlink /$file). Keep it."
+        fi
     else
         echo install $file
-        if [ -e /$file ]
-        then
+        if [ -d /$file ]; then
+            echo "/$file is a directory, but $file is not. Exiting..."
+            exit $E_BADFILE
+        elif [ -e /$file ]; then
             echo /$file exists
-            handle_collision $file && cp --preserve=mode --no-dereference $file / || echo $file >> .FAILED
+            handle_collision $file && cp --preserve=mode --no-dereference $file / || echo $file >> $failed
         else
             cp --preserve=mode --no-dereference $file /
         fi
     fi
-    sed -i "1d" .TMP
-done 4<.TMP
+    sed -i "1d" $list
+done 4<$list
 
-if [ -f .INFO ]; then
-    install_info .INFO
+if [ -f $info ]; then
+    install_info $info
 fi
 
-check_collision() {
-    if [ $# -ne 1 ]
-    then
-        return $E_WARGS
-    fi
+if [ -f $etc ]; then
+    install_etc $etc
+fi
 
-    local list=$1
+cp $list $currents/$pf.list
+
+rm -r $tmpdir
+
+# Main finished. Now comes the definitions
+
+parse_list() {
     local file
-    local conffile=.CONFLICT
-    local conflict
+    local otherpkg
 
-    rm $conffile
+    rm $conflict
 
+    # check for info
+    grep "\.info$" $list > $info
+    # remove etcs from $list
+    grep "^etc/" > $etc
+    sed -i "\:^etc/:d" $list
+
+    # now check for conflicts
     while read file
     do
-        if [ ! -d $file -a -e $file ]
-        then
-            conflict=$(find_belongs $file)
-            if [ "$conflict" != "$pkgfname" ]
-            then
-                echo "$file : $conflict" >> $conffile
-            fi
+        if [ ! -d /$file -a -e /$file ]; then
+            otherpkg=$(find_belongs $file) # $file should be without leading /
+            echo "$file : $otherpkg" >> $conflict
         fi
     done <$list
 
-    if [ -f $conffile ] && [ "$(cut -d' ' -f1 <<<$(wc -l $conffile))" -gt "0" ]
+    if [ -f $conflict ] && [ "$(cut -d' ' -f1 <<<$(wc -l $conflict))" -gt "0" ]
     then
-        vim $conffile &&
-        handle_conffile $conffile
+        vim $conflict &&
+        handle_conflict
     fi
 }
 
@@ -104,98 +124,83 @@ find_belongs() {
         return $E_WARGS
     fi
 
-    local line=$(head -n1 <<< $(grep "^$1$" $currents/*))
-    local list=$(cut -d":" -f1 <<< "$line")
+    local line=$(head -n1 <<< $(grep "^$1$" $currents/*)) # head seems to be some magic here that joins the lines?
+    line=$(cut -d":" -f1 <<< "$line")
 
-    if [[ "z$list" == "z" ]]
-    then
+    if [[ "z$line" == "z" ]]; then
         return 0
     fi
 
-    list=$(basename ${list%.*})
-
-    echo $list
+    line=$(basename ${line%.*})
+    echo $line
 }
 
-handle_conffile() {
-    if [ $# -ne 1 ]
-    then
-        return $E_WARGS
-    fi
-    local conffile=$1
+handle_conflict() {
+    local line
     local file
     local cpkg
 
     while read line
     do
-        file=$(cut -d':' -f1 <<<"$(sed -e 's/^#//' <<<$line)")
+        file=$(cut -d':' -f1 <<<"$(sed -e 's/^#//' <<<$line)") # $file should be without leading /
         cpkg=$(cut -d':' -f2 <<<"$(sed -e 's/^#//' <<<$line)")
         if grep -q '^#' <<<"$line" # with '#', we mean that we want to keep the old file
         then
             echo "Will keep old $file"
-            rm_from_fakeroot $file "conflict"
+            rm_from_pkg $file $cpkg
         else
             echo "Will remove old $file"
             if [ ! "$cpkg" ]
             then
-                sys_backup_file $file "conflict"
+                sys_backup_file $file
             else
-                recollect_file $file $cpkg "conflict"
+                recollect_file $file $cpkg
             fi
         fi
-    done <$conffile
+    done <$conflict
+}
+
+rm_from_pkg() {
+    if [ $# -lt 1 ] # $2 is the conflicted package, if any
+    then
+        return $E_WARGS
+    fi
+
+    local file=$1
+    local cf=$2
+
+    echo removing $file from $pf
+    sed -i "\:^${file}$:d" $list &&
+
+    tar -rf $backupdir/$pf-$cf.tar $file &&
+    rm $file
 }
 
 sys_backup_file() {
-    if [ $# -lt 2 ]
+    if [ $# -lt 1 ] # $1 is the file to backup
     then
         return $E_WARGS
     fi
 
-    local file=$1
-    local name=$2
-
-    echo removing $file from system
-    tar rf $pkgs/backup/$name.tar $file &&
-    rm $file
-}
-
-rm_from_fakeroot() {
-    if [ $# -lt 2 ]
-    then
-        return $E_WARGS
-    fi
-
-    local file=$1
-    local name=$2
-
-    echo removing $file from $pkgfname
-    sed -i "\:^${file}$:d" $listfile &&
-
-    file=${file#/}
-    tar -C $fakeroot -rf $verdir/backup/$pkgfname-$name.tar $file &&
-    rm $fakeroot/$file
+    echo removing /$1 from system
+    tar rf $backupdir/conflict.tar /$1 &&
+    rm /$1
 }
 
 recollect_file() {
-    if [ $# -lt 3 ]
+    if [ $# -lt 2 ]
     then
         return $E_WARGS
     fi
 
     local file=$1
-    local p=$(cut -d'-' -f1 <<<"$2")
-    local v=$(cut -d'-' -f2 <<<"$2")
-    local a=$(cut -d'-' -f3 <<<"$2")
-    local f=$p-$v-$a
-    local vd=$pkgs/$p/$v
-    local list=$pkgs/$p/$v/${f}.list
-    local name=$3
+    local cf=$2
+    local clist=$currents/${cf}.list
 
-    echo removing $file from $p $v $a
-    sed -i "\:^${file}$:d" $list &&
-    tar rf $vd/backup/$f-$name.tar $file &&
-    rm $file
+    echo removing /$file from $cf
+    sed -i "\:^${file}$:d" $clist &&
+    tar rf $backupdir/$cf-$pf.tar /$file &&
+    rm /$file
 }
 
 handle_collision() {  # this is not good enough
@@ -205,11 +210,6 @@ handle_collision() {  # this is not good enough
     fi
 
     local conflict=$(find_belongs $1)
-
-    if [ z"$conflict" == z"${pkg}-${arch}" ]
-    then
-        return 0
-    fi
 
     if [ "$conflict" ]
     then
